enum HttpStatusCodes {
  STATUS_CODE_OK = 200,
  STATUS_CODE_CREATED = 201,
  STATUS_CODE_NO_CONTENT = 204,
  STATUS_CODE_FOUND = 302,
  STATUS_CODE_BAD_REQUEST = 400,
  STATUS_CODE_FORBIDDEN = 403,
  STATUS_CODE_NOT_FOUND = 404,
  STATUS_CODE_CONFLICT = 409,
  STATUS_CODE_UUNPROCESSABLE_ENTITY = 422,
  STATUS_CODE_INTERNAL_SERVER_ERROR = 500,
}

export { HttpStatusCodes };
